### ISSUE TITLE
Bug: Bug report icon on website is lower than surrounding text

### ISSUE THREAD

**Issue by IanDuncanT** [CollegeFootballRisk/Risk#22]
**Describe the bug**
The report a bug icon in the menu bar is lower than the surrounding menu items.

**To Reproduce**
1. Go to https://aggierisk.ml
2. See error

**Expected behavior**
Bug icon is level with surrounding text.

**Screenshots**
Screenshot with added lines for top/bottom of text.
<img width="467" alt="Screen Shot 2020-08-27 at 12 46 29 AM" src="https://user-images.githubusercontent.com/39711921/91390029-e4874080-e7fe-11ea-9375-b48731050068.png">

**Comment by mautamu** [comment]
Which browser is this?

Firefox 81.0b2-1/Brave 1.13.78-1 appear to render this correctly.

**Comment by IanDuncanT** [comment]
Safari Version 13.1.2 (15609.3.5.1.3)

**Comment by mautamu** [comment]
- [x] Remove bug icon and replace with a dropdown menu
- [x] Investigate error box more


~https://github.com/flutter/flutter/issues/28894~

**Comment by mautamu** [comment]
Going to close this for now, emoji has been replaced with text.
